"""Exercise the delivered matter UI and its request payloads with fictional data.

The VM evaluates the production script; the transport and minimal document stub
let us control late replies, conflicts and repeated submissions without a real DB.
"""
from pathlib import Path
import shutil
import subprocess

import pytest

ROOT = Path(__file__).resolve().parents[1]
NODE = shutil.which("node")
HARNESS = r'''
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const root=process.argv[1],test=process.argv[2],listeners=new Map(),calls=[],responses=[],dialogs=[],notices=[];
const state={csrf:'fictional-session',authenticated:true,view:'records',page:1,q:'',customer:'',dialogIntentGeneration:0,detail:null};
let sequence=0,loads=0;
const context={state,Date,Math,Map,Set,URLSearchParams,Promise,Object,Array,String,Number,JSON,Boolean,Intl,
 document:{addEventListener:(name,fn,capture)=>{if(!listeners.has(name))listeners.set(name,[]);listeners.get(name).push({fn,capture});},createElement:()=>{throw new Error('late refresh must not touch a new document');}},
 icon:()=>'<svg aria-hidden="true"></svg>',heading:(title,description,extra)=>`<h1>${title}</h1><p>${description}</p>${extra}`,
 customerOptions:()=>'',formatDate:(timestamp,full)=>timestamp?`TIME-${timestamp}`:'待补时间',
 dialogHeader:(title,description)=>`<h2>${title}</h2><p>${description}</p>`,
 flowComposer:(plan,scope,home,key)=>`<form data-flow-form data-id="${key}"><div class="flow-current"><strong>新的一件事 · 随口告诉秘书</strong></div><label>想到什么，先告诉秘书</label><textarea placeholder="如：10月8日约林博士吃饭。或：刚和客户聊完，想法先记在这里。"></textarea><input name="attachment_items"><button type="submit">告诉秘书</button></form>`,
 newVisitRequestKey:()=>`fictional-request-${++sequence}`,formValues:form=>form.values,
 $:(selector,form)=>{if(selector==='.form-error')return form?.error||null;if(selector==='button[type="submit"]')return form?.submit||null;if(selector==='[data-matter-reload-preview]')return null;if(selector==='#detail-content')return {};return null;},
 $$:(selector,form)=>selector.includes(':checked')?(form?.checks||[]).filter(input=>input.checked):form?.checks||[],
 openDialog:(kind,html)=>{state.dialogIntentGeneration++;dialogs.push({kind,html});},closeDialog:()=>{},flowRestore:()=>{},
 notify:(text,error)=>notices.push({text,error}),clearDraft:()=>{},loadView:async()=>{loads++;},
 api:async(url,options={})=>{calls.push({url,options});assert(responses.length,`unexpected API request: ${url}`);const next=responses.shift();if(next instanceof Error)throw next;if(typeof next==='function')return await next();return next;}
};
vm.createContext(context);
const app=fs.readFileSync(path.join(root,'secretary/static/app.js'),'utf8');
vm.runInContext(app.slice(app.indexOf('const escapeHTML ='),app.indexOf('const paths =')),context);
vm.runInContext(app.split('\n').find(line=>line.startsWith('function dialogHeader(')),context);
vm.runInContext(fs.readFileSync(path.join(root,'secretary/static/matters.js'),'utf8'),context);
function matter(extra={}){return {id:1,title:'准备电力产品汇报',objective:'让客户了解应用与试点方案',status:'following',visibility:'active',revision:3,customer_id:8,customer_name:'示例单位',opportunity_id:5,project_name:'示例项目',action_count:2,completed_action_count:0,next_action:{id:21,title:'调整PPT结构'},next_schedule:null,actions:[{id:21,title:'调整PPT结构',status:'following',content:'按产品线整理'},{id:22,title:'补充装置内容',status:'following'}],sources:[{id:20,title:'汇报准备原话',content:'原始沟通'}],tasks:[],plans:[],materials:[],visits:[],events:[],operations:[],...extra};}
function form(kind,values={},extra={}){const more={...extra};delete more.dataset;return {dataset:{matterForm:kind,matterId:'1',matterRevision:'3',...extra.dataset},values,checks:extra.checks||[],isConnected:true,closest:()=>({open:true}),error:{textContent:'',insertAdjacentHTML:(where,html)=>{}},submit:{disabled:false,isConnected:true},...more};}
const plain=value=>JSON.parse(JSON.stringify(value));
async function run(){
 if(test==='one_goal_many_actions'){const html=context.matterCardHTML(matter());assert.equal(html.split('data-matter-card=').length-1,1);assert(html.includes('0 / 2 个动作已完成'));assert(html.includes('展开动作'));assert(html.includes('data-raw-record="21"'));assert(!html.includes('data-complete-task'));}
 else if(test==='detail_one_composer'){const html=context.matterDetailHTML(matter());assert.equal(html.split('data-flow-form').length-1,1);assert(html.includes('data-matter-id="1" data-matter-revision="3"'));assert(html.includes('data-id="matter-1"'));assert(html.includes('继续补充这件事'));assert(html.includes('attachment_items'));assert(html.includes('data-discussion-matter="1"'));assert(html.includes('data-raw-record="21"'));assert(!html.includes('data-record="21"'));}
 else if(test==='closed_no_composer'){for(const extra of [{status:'ended',outcome:'achieved'},{visibility:'archived'},{visibility:'trash'}]){const html=context.matterDetailHTML(matter(extra));assert(!html.includes('data-flow-form'));assert(!html.includes('data-start-discussion'));assert(html.includes(extra.status?'目标达成':'恢复'));assert(html.includes('历史讨论仍可在历程中回看'));} }
 else if(test==='ended_card_no_continue_claim'){const html=context.matterCardHTML(matter({status:'ended',outcome:'achieved'}));assert(html.includes('回看结果'));assert(html.includes('这件事已结束'));assert(!html.includes('继续这件事'));assert(!html.includes('<span>下一步</span> 调整PPT结构'));}
 else if(test==='no_invented_time'){assert.equal(context.matterScheduleText({date:'2026-10-11',status:'preparing'}),'2026-10-11 · 时间待定 · 待约 / 待完善');assert(!context.matterScheduleText({date:'2026-10-11'}).includes('00:00'));assert(context.matterScheduleText({date:'2026-10-11',time:'18:30',status:'preparing'}).includes('18:30'));}
 else if(test==='schedule_one_activity'){const html=context.matterScheduleHTML(matter({tasks:[{id:7,title:'同一次汇报',remind_at:123,record_id:21,status:'pending'}],plans:[{id:6,task_id:7,title:'同一次汇报',status:'scheduled'},{id:8,title:'另一次待约',date:'2026-10-11',status:'preparing'}]}));assert.equal(html.split('同一次汇报').length-1,1);assert(html.includes('data-raw-plan="8"'));assert(html.includes('data-raw-record="21"'));}
 else if(test==='complete_step_not_goal'){const html=context.matterDetailHTML(matter({actions:[{id:21,title:'材料已做',status:'done'}]}));assert(html.includes('跟进中'));assert(html.includes('待完成动作 · 0'));assert(html.includes('已完成动作 · 1'));assert(html.includes('动作完成后仍可继续跟进'));}
 else if(test==='escaped_business_text'){const html=context.matterDetailHTML(matter({title:'<img src=x onerror=alert(1)>',objective:'<script>x</script>',next_action:{title:'" onclick="oops'},sources:[{id:20,title:'<b>x</b>',original_content:'<script>unsafe</script>'}],materials:[{id:'" onclick="x',title:'<iframe>x</iframe>'}],events:[{id:1,type:'source',title:'<svg>',text:'<script>history</script>'}]}));assert(!html.includes('<script>'));assert(!html.includes('<img '));assert(!html.includes('<iframe>'));assert(html.includes('&lt;script&gt;'));assert(html.includes('&quot;'));}
 else if(test==='multi_goal_context'){const html=context.matterContextHTML([matter(),matter({id:2,title:'另一个目标'})]);assert(html.includes('data-matter-open="1"'));assert(html.includes('data-matter-open="2"'));assert(html.includes('日程仍只计算一次'));assert.equal(context.matterContextHTML([]),'');}
 else if(test==='route_receipt_and_choices'){let html=context.matterTurnHTML({id:40,matter_id:1,matter_route:{kind:'existing',title:'汇报目标'}});assert(html.includes('已补入事项'));assert(html.includes('data-matter-route-correct="40"'));html=context.matterTurnHTML({id:41,result:{matter_route:{kind:'ambiguous',candidates:[{matter_id:2,title:'候选一'},{id:3,title:'候选二'}]}}});assert(html.includes('data-matter-route-choice="2"'));assert(html.includes('data-matter-route-choice="3"'));assert(html.includes('data-matter-route-fresh="41"'));assert.equal(context.matterTurnHTML({result:{}}),'');}
 else if(test==='queued_receipt_not_false_success'){const html=context.matterTurnHTML({id:42,status:'queued',matter_id:1,matter:{title:'这件事'}});assert(html.includes('原话已保存，正在整理这件事'));assert(!html.includes('已补入事项'));assert(!html.includes('归错了'));}
 else if(test==='list_pagination_by_goals'){responses.push({items:[matter()],total:23,page:2,pages:2,ungrouped_count:3,summary:{action_count:9}});state.page=2;state.q='产品';const html=await context.renderMatters();assert(calls[0].url.includes('page=2'));assert(calls[0].url.includes('visibility=active'));assert(html.includes('共 23 件事'));assert(html.includes('23 件事 · 9 个动作'));assert(html.includes('3 条未归组'));assert(html.includes('data-matter-raw-list'));}
 else if(test==='empty_and_error'){responses.push({items:[],total:0});let html=await context.renderMatters();assert(html.includes('先告诉秘书一件事'));state.q='不存在';responses.push({items:[],total:0});html=await context.renderMatters();assert(html.includes('没有匹配的事项'));responses.push(new Error('network'));await assert.rejects(()=>context.openMatter(1),/network/);assert.equal(dialogs.length,0);}
 else if(test==='late_open_never_steals_focus'){let resolve;responses.push(()=>new Promise(r=>resolve=r));const promise=context.openMatter(1);state.dialogIntentGeneration++;resolve({matter:matter()});await promise;assert.equal(dialogs.length,0);assert.equal(state.detail,null);}
 else if(test==='logout_cannot_reopen'){let resolve;responses.push(()=>new Promise(r=>resolve=r));const promise=context.openMatter(1);state.authenticated=false;state.csrf='';resolve({matter:matter()});await promise;assert.equal(dialogs.length,0);}
 else if(test==='open_same_matter'){responses.push({matter:matter()});await context.openMatter(1);assert.equal(state.detail.type,'matter');assert.equal(state.detail.id,1);assert.equal(dialogs[0].kind,'detail');assert(dialogs[0].html.includes('正在补充：准备电力产品汇报'));}
 else if(test==='require_explicit_end_reason'){const current=form('edit',{title:'目标',objective:'结果',status:'ended',outcome:''});await context.submitMatterForm(current);assert.equal(calls.length,0);assert(current.error.textContent.includes('请选择目标达成或不再推进'));assert.equal(current.submit.disabled,false);}
 else if(test==='stable_retry_request'){const current=form('edit',{title:'目标',objective:'结果',status:'waiting',outcome:''});responses.push(new Error('连接暂时失败'));await context.submitMatterForm(current);const first=plain(calls[0].options.body);responses.push({matter:matter()},{matter:matter()});await context.submitMatterForm(current);const second=plain(calls[1].options.body);assert.equal(first.request_id,second.request_id);assert.equal(second.expected_revision,3);assert.equal(second.status,'waiting');assert.equal(calls[1].options.method,'PATCH');}
 else if(test==='double_submit_once'){let resolve;const current=form('edit',{title:'目标',objective:'结果',status:'following'});responses.push(()=>new Promise(r=>resolve=r));const promise=context.submitMatterForm(current);await context.submitMatterForm(current);assert.equal(calls.length,1);current.isConnected=false;resolve({matter:matter()});await promise;assert.equal(dialogs.length,0);}
 else if(test==='candidate_subset_preserves_sources'){const current=form('candidate',{title:'共同目标',objective:'一件事'},{dataset:{matterForm:'candidate',matterKey:'source:20',matterFingerprint:'abc'},checks:[{value:'21',checked:true},{value:'22',checked:false}]});current.isConnected=false;responses.push({matter:matter()});await context.submitMatterForm(current);assert.equal(calls[0].url,'/api/matters/candidates/confirm');assert.deepEqual(plain(calls[0].options.body.action_record_ids),[21]);assert.equal(calls[0].options.body.fingerprint,'abc');assert(!('source_record_ids' in calls[0].options.body));}
 else if(test==='merge_revision_both_goals'){const html=context.matterMergePreviewHTML(matter(),matter({id:2,revision:8,title:'保留目标'}));assert(html.includes('data-matter-target="2"'));assert(html.includes('data-matter-target-revision="8"'));assert(html.includes('不创建重复提醒'));const current=form('merge',{}, {dataset:{matterTarget:'2',matterTargetRevision:'8'}});current.isConnected=false;responses.push({matter:matter({id:2})});await context.submitMatterForm(current);assert.deepEqual(plain(calls[0].options.body),{target_id:2,expected_revision:3,target_revision:8,request_id:'fictional-request-1'});}
 else if(test==='split_preview_selective'){const html=context.matterSplitPreviewHTML(matter(),{title:'独立目标',objective:'另一个结果'},[22]);assert(html.includes('补充装置内容'));assert(!html.includes('调整PPT结构'));assert(html.includes('data-matter-action-ids="[22]"'));assert(html.includes('不会新建或重发提醒'));}
 else if(test==='split_opens_new_goal_and_links_original'){const original=matter({revision:4}),newGoal=matter({id:2,title:'新的独立目标',revision:1}),current=form('split',{title:'新的独立目标',objective:'不同结果'},{dataset:{matterActionIds:'[22]'}});responses.push({matter:original,related_matters:[newGoal]},{matter:newGoal});await context.submitMatterForm(current);assert.equal(calls[0].url,'/api/matters/1/split');assert.equal(calls[1].url,'/api/matters/2');assert.equal(state.detail.id,2);const html=context.matterOperationResultHTML({matter:original,related_matters:[newGoal]},'split');assert(html.includes('data-matter-open="1"'));assert(html.includes('data-matter-open="2"'));assert(html.includes('所选动作已转到新事项'));}
 else if(test==='lifecycle_preview_shared_and_restore'){let html=context.matterLifecycleHTML(matter(),{snapshot:'s',pending_tasks:[{title:'现有会面',remind_at:123}],shared_tasks:1,pending_proposal_count:2},'archived');assert(html.includes('1 条还被其他事项或记录使用'));assert(html.includes('2 条待确认安排'));assert(html.includes('保留已有安排与提醒'));assert(html.includes('日程仍然生效'));assert(html.includes('name="snapshot" value="s"'));html=context.matterLifecycleHTML(matter({visibility:'archived'}),{snapshot:'s'},'active');assert(html.includes('已经停止或取消的提醒保持停止'));assert(!html.includes('value="cancel"'));}
 else if(test==='cancel_snapshot_payload'){const current=form('lifecycle',{snapshot:'current-hash',reminder_action:'cancel'},{dataset:{matterVisibility:'archived'}});current.isConnected=false;responses.push({matter:matter({visibility:'archived'})});await context.submitMatterForm(current);assert.deepEqual(plain(calls[0].options.body),{visibility:'archived',expected_revision:3,reminder_action:'cancel',snapshot:'current-hash',request_id:'fictional-request-1'});}
 else if(test==='keep_radio_does_not_cancel'){const current=form('lifecycle',{snapshot:'current-hash',reminder_action:'cancel'},{dataset:{matterVisibility:'archived'},elements:{namedItem:name=>name==='reminder_action'?{value:'keep'}:null}});current.isConnected=false;responses.push({matter:matter({visibility:'archived'})});await context.submitMatterForm(current);assert.equal(calls[0].options.body.reminder_action,'keep');}
 else if(test==='undo_uses_operation_owner'){const html=context.matterUndoHTML(matter({operations:[{id:11,operation:'merge',matter_id:2,created_at:123,undoable:true},{id:12,operation:'update',matter_id:1,undoable:false}]}));assert(html.includes('data-matter-undo-preview="11" data-matter-id="2"'));assert(!html.includes('data-matter-undo-preview="12"'));assert(html.includes('合并事项'));const current=form('undo',{}, {dataset:{matterOperation:'11',matterRevision:'8'}});current.isConnected=false;responses.push({matter:matter()});await context.submitMatterForm(current);assert.equal(calls[0].url,'/api/matters/operations/11/undo');assert.equal(calls[0].options.body.expected_revision,8);}
 else if(test==='stale_revision_keeps_input'){const error=new Error('已有新进展');error.status=409;responses.push(error);const current=form('edit',{title:'未发送的新目标',objective:'修改仍保留',status:'following'});await context.submitMatterForm(current);assert.equal(current.values.title,'未发送的新目标');assert.equal(current.error.textContent,'已有新进展');assert.equal(dialogs.length,0);assert.equal(current.submit.disabled,false);}
 else if(test==='overview_caps_six'){const html=context.matterOverviewHTML({items:Array.from({length:8},(_,index)=>matter({id:index+1,title:'目标'+index})),summary:{following:8,waiting:2},ungrouped_count:3});assert.equal(html.split('data-matter-card=').length-1,6);assert(html.includes('8 件跟进中 · 2 件等待反馈'));assert(html.includes('data-matter-list'));}
 else if(test==='late_refresh_preserves_new_context'){state.detail={type:'matter',id:1};let resolve;const original={dataset:{matterId:'1',matterRevision:'3'},isConnected:true,closest:()=>({open:true}),text:{value:'用户后续未发送的内容'}};responses.push(()=>new Promise(r=>resolve=r));const promise=context.refreshMatterAfterTurn({id:88},original);state.detail={type:'matter',id:2};state.dialogIntentGeneration++;resolve({matter:matter({revision:5})});await promise;assert.equal(original.text.value,'用户后续未发送的内容');assert.equal(original.dataset.matterRevision,'3');assert.equal(dialogs.length,0);}
 else if(test==='source_resolution_owner_transport'){responses.push({items:[matter()]});const items=await context.matterResolve('record',20);assert.equal(items.length,1);assert.equal(calls[0].url,'/api/matters/resolve?entity_type=record&entity_id=20');const invalid=await context.matterResolve('unsafe',20);assert.equal(invalid.length,0);}
 else if(test==='resolved_original_without_goal'){responses.push({items:[]});const handled=await context.openResolvedMatter('record',20);assert.equal(handled,false);assert.equal(dialogs.length,0);}
 else if(test==='resolved_single_goal_opens'){responses.push({items:[matter()]},{matter:matter()});const handled=await context.openResolvedMatter('plan',7);assert.equal(handled,true);assert.equal(state.detail.type,'matter');assert.equal(state.detail.id,1);assert.equal(dialogs[0].kind,'detail');}
 else if(test==='resolved_multiple_goals_choose'){responses.push({items:[matter(),matter({id:2,title:'第二个目标'})]});const handled=await context.openResolvedMatter('task',7);assert.equal(handled,true);assert.equal(dialogs[0].kind,'edit');assert(dialogs[0].html.includes('关联了多个目标'));assert(dialogs[0].html.includes('data-matter-open="1"'));assert(dialogs[0].html.includes('data-matter-open="2"'));assert.equal(state.detail,null);}
 else if(test==='all_mutation_forms_have_proxy_ids'){for(const kind of ['edit','split-preview','split','merge-preview','merge','undo','lifecycle']){const attrs=context.matterMutationFormAttrs(matter(),kind);assert(attrs.includes(`id="matter-${kind}-form"`));assert(attrs.includes('data-id="1"'));assert(attrs.includes('data-revision="3"'));}const html=context.matterLifecycleHTML(matter(),{snapshot:'s'},'archived');assert(html.includes('id="matter-lifecycle-form"'));assert(html.includes('name="reminder_action"><option value="keep" selected'));assert(!html.includes('type="radio"'));}
 else if(test==='candidate_checks_have_separate_drafts'){responses.push({items:[{key:'source:20',fingerprint:'stable',title:'共同目标',objective:'结果',action_record_ids:[21,22],source_record_ids:[20],actions:matter().actions}]});await context.openMatterCandidates();await context.openMatterCandidatePreview('source:20');const html=dialogs.at(-1).html;assert(html.includes('id="matter-candidate-form"'));assert(html.includes('data-id="source:20" data-revision="stable"'));assert(html.includes('name="matter_action_21" data-matter-action-id="21"'));assert(html.includes('name="matter_action_22" data-matter-action-id="22"'));assert(!html.includes('name="action_record_ids"'));assert.equal(calls.length,1);}
 else if(test==='real_draft_restore_preserves_action_subset'){for(const name of ['formValues','resetVisitSourceReason','syncVisitSourceTime','applyDraftValues']){const line=app.split('\n').find(line=>line.startsWith(`function ${name}(`));assert(line);vm.runInContext(line,context);}const current=form('candidate',{}, {id:'matter-candidate-form',checks:[{name:'matter_action_21',value:'21',type:'checkbox',checked:true},{name:'matter_action_22',value:'22',type:'checkbox',checked:false}]});const saved=context.formValues(current);assert.deepEqual(plain(saved),{matter_action_21:true,matter_action_22:false});current.checks[0].checked=false;current.checks[1].checked=true;context.applyDraftValues(current,saved);assert.equal(current.checks[0].checked,true);assert.equal(current.checks[1].checked,false);}
 else if(test==='restore_keeps_cancelled_reminders_stopped'){const current=form('lifecycle',{snapshot:'current-hash',reminder_action:'keep'},{dataset:{matterVisibility:'active'}});current.isConnected=false;responses.push({matter:matter()});await context.submitMatterForm(current);assert.equal(calls[0].options.body.visibility,'active');assert.equal(calls[0].options.body.reminder_action,'keep');assert(!('restart_reminders' in calls[0].options.body));}
 else if(test==='raw_list_and_return_navigation'){const handler=listeners.get('click').find(item=>item.capture).fn,button={dataset:{matterRawList:''},isConnected:true,disabled:false},event={target:{closest:()=>button},preventDefault:()=>{},stopImmediatePropagation:()=>{}};await handler(event);assert.equal(state.matterRawRecords,true);assert.equal(loads,1);button.dataset={matterList:''};context.navigate=async view=>{assert.equal(view,'records');loads++;};await handler(event);assert.equal(state.matterRawRecords,false);assert.equal(loads,2);}
 else if(test==='merge_cross_scope_not_confirmable'){for(const changed of [{customer_id:99},{opportunity_id:99},{opportunity_id:null}]){const html=context.matterMergePreviewHTML(matter(),matter({...changed,id:2}));assert(html.includes('不能合并不同归属'));assert(!html.includes('data-matter-form="merge"'));assert(!html.includes('确认合并'));}}
 else if(test==='history_has_original_entry_targets'){const html=context.matterHistoryHTML(matter({tasks:[{id:8,record_id:21}],events:[{type:'source',id:20,title:'原话',created_at:1},{type:'action',id:21,title:'动作',created_at:2},{type:'schedule',id:8,title:'活动',created_at:3},{type:'discussion',id:5,thread_id:9,title:'推进讨论',role:'assistant',text:'下一步建议',created_at:4},{type:'operation',id:6,title:'confirm_candidate',created_at:5}]}));assert(html.includes('确认历史归组'));assert(!html.includes('>confirm_candidate<'));assert(html.includes('data-raw-record="20"'));assert(html.includes('data-raw-record="21"'));assert(html.includes('data-discussion-thread="9"'));assert(html.indexOf('确认历史归组')<html.indexOf('推进讨论'));}
 else if(test==='refresh_keeps_composer_and_attachments'){
   const selectors=['.matter-focus','[data-matter-section="schedules"]','[data-matter-section="actions"]','[data-matter-section="history"]','[data-matter-section="materials"]'];
   const originalParts=new Map(selectors.map(selector=>[selector,{innerHTML:'old',tagName:selector.includes('history')||selector.includes('materials')?'DETAILS':'SECTION',open:true}]));
   const freshParts=new Map(selectors.map(selector=>[selector,{innerHTML:'new-persisted-evidence'}])),rootNode={dataset:{matterRevision:'3'}},freshRoot={};
   const original={dataset:{matterId:'1',matterRevision:'3'},isConnected:true,text:{value:'新的未发送内容'},attachments:{value:'[fictional-file]'},closest:selector=>selector==='dialog'?{open:true}:rootNode};
   const oldDollar=context.$;context.$=(selector,root)=>root===rootNode?originalParts.get(selector)||null:root===freshRoot?freshParts.get(selector)||null:selector==='[data-matter-detail]'?freshRoot:oldDollar(selector,root);
   let generated='';context.document.createElement=()=>({set innerHTML(value){generated=value;}});state.detail={type:'matter',id:1,revision:3};responses.push({matter:matter({revision:5})});await context.refreshMatterAfterTurn({id:90},original);
   assert(generated.includes('data-matter-revision="5"'));assert.equal(original.text.value,'新的未发送内容');assert.equal(original.attachments.value,'[fictional-file]');assert.equal(original.dataset.matterRevision,5);assert.equal(state.detail.revision,5);assert.equal(originalParts.get('[data-matter-section="history"]').open,true);assert.equal(originalParts.get('.matter-focus').innerHTML,'new-persisted-evidence');assert.equal(dialogs.length,0);
 }
 else throw new Error('unknown scenario '+test);
}
run().catch(error=>{process.stderr.write(error.stack+'\n');process.exitCode=1;});
'''

SCENARIOS = [
    "one_goal_many_actions", "detail_one_composer", "closed_no_composer",
    "ended_card_no_continue_claim",
    "no_invented_time", "schedule_one_activity", "complete_step_not_goal",
    "escaped_business_text", "multi_goal_context", "route_receipt_and_choices",
    "queued_receipt_not_false_success",
    "list_pagination_by_goals", "empty_and_error", "late_open_never_steals_focus",
    "logout_cannot_reopen", "open_same_matter", "require_explicit_end_reason",
    "stable_retry_request", "double_submit_once", "candidate_subset_preserves_sources",
    "merge_revision_both_goals", "split_preview_selective",
    "split_opens_new_goal_and_links_original",
    "lifecycle_preview_shared_and_restore", "cancel_snapshot_payload",
    "keep_radio_does_not_cancel",
    "undo_uses_operation_owner", "stale_revision_keeps_input", "overview_caps_six",
    "late_refresh_preserves_new_context", "source_resolution_owner_transport",
    "resolved_original_without_goal", "resolved_single_goal_opens",
    "resolved_multiple_goals_choose", "merge_cross_scope_not_confirmable",
    "all_mutation_forms_have_proxy_ids", "restore_keeps_cancelled_reminders_stopped",
    "candidate_checks_have_separate_drafts",
    "real_draft_restore_preserves_action_subset",
    "raw_list_and_return_navigation",
    "history_has_original_entry_targets", "refresh_keeps_composer_and_attachments",
]


@pytest.mark.skipif(not NODE, reason="Node.js required for delivered browser script")
@pytest.mark.parametrize("scenario", SCENARIOS)
def test_matters_frontend(scenario):
    result = subprocess.run(
        [NODE, "-e", HARNESS, str(ROOT), scenario], capture_output=True,
        text=True, encoding="utf-8", timeout=20,
    )
    assert result.returncode == 0, result.stdout + result.stderr
